"""Add category and contact_email

Revision ID: 30495cf5a12a
Revises: 0003_discovery_tables
Create Date: 2026-10-05 21:14:16.905398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30495cf5a12a'
down_revision: Union[str, Sequence[str], None] = '0003_discovery_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'category')
    # ### end Alembic commands ###
